### ISSUE TITLE
setting proxy

### ISSUE THREAD

**Issue by donnyc219** [googleapis/nodejs-recaptcha-enterprise#231]
Hello.

Is there a way to set proxy in this library?

My code works perfectly in my local machine but not in PCF. Found out that it is a proxy issue.

Thanks.

**Comment by bcoe** [comment]
@donnyc219 you should be able to set the environment variable `http_proxy` or `grpc_proxy`, or `https_proxy. Let us know if that does the trick?

**Comment by donnyc219** [comment]
@bcoe Ya it works! I added `HTTPS_PROXY` as an environment variable.

Thank you!

For anyone who encounters the same issue and want to know more:
https://medium.com/google-cloud/accessing-google-cloud-apis-though-a-proxy-fe46658b5f2a

**Comment by harshadbankar** [comment]
I have same requirement, but request does not pass through proxy server. (getting 504 error)
If I see code, below domains are used to make assessment request:
 
_https://recaptchaenterprise.googleapis.com
https://www.googleapis.com
Https://cloudresourcemanager.googleapis.com_

Our infra team tried to curl to all above domains via proxy, that works.
Is there anything I am missing?!

**Comment by bcoe** [comment]
@harshadbankar how are you setting the proxy variable?

**Comment by harshadbankar** [comment]
Getting `Error: 4 DEADLINE_EXCEEDED`
Setting `grpc_proxy` env variable on start of node server
(Looked up in grpc lib, they ask to set `grpc_proxy` which I see library also respecting)
If I use `fallback: true` when initialising `RecaptchaEnterpriseServiceClient`, it works in local. but `fallback: true` uses browser http protocol, which does not respect nodejs proxy env variables.

**Comment by bcoe** [comment]
@harshadbankar could you please run your application with the environment variables:

```
GRPC_TRACE=all GRPC_VERBOSITY=DEBUG
```

And provide the output.

**Comment by harshadbankar** [comment]
[error.txt](https://github.com/googleapis/nodejs-recaptcha-enterprise/files/6133648/error.txt)
FYI: IP `1.1.1.1` and `demo.proxy.com` in log are replacement of proxy domain i am using.

**Comment by harshadbankar** [comment]
If i do second try immediately, below log i see in terminal.
[error-second-try.txt](https://github.com/googleapis/nodejs-recaptcha-enterprise/files/6133657/error-second-try.txt)

**Comment by bcoe** [comment]
@harshadbankar could you send me the entire log by email bencoe [at] google.com.

**Comment by furkee** [comment]
hey @bcoe, i am also having a problem with the proxy. logs are saying successfully connected to googleapis through the proxy but the actual call later fails with `No connection established`.  i used every possible proxy env variable combination: grpc_proxy, both lowercase and uppercase http_proxy, https_proxy.

logs (using a local proxy setup with an app called mitmproxy): [recaptcha.error.txt](https://github.com/googleapis/nodejs-recaptcha-enterprise/files/6709916/recaptcha.error.txt)

do you have any suggestions?

**Comment by bcoe** [comment]
@furkee thank you for sharing the logs, I don't have any immediate ideas but I can surface the bug with our gRPC folks.

**Comment by furkee** [comment]
@bcoe thanks for forwarding the issue. is there link i can follow, like another issue on github?

**Comment by bcoe** [comment]
@furkee see:

https://github.com/grpc/grpc-node/issues/1841

I'm closing this issue because @donnyc219's initial problem has been addressed, @harshadbankar If you are continuing to bump into issues, could I ask you to open a new issue that describes the specific problems you're running into?
