### ISSUE TITLE
How to use it for ReCaptcha V2 ( with checkbox ) ?

### ISSUE THREAD

**Issue by BeingShaashi** [googleapis/nodejs-recaptcha-enterprise#240]
Hi,

I want to know if we can use the same SDK to verify the token sent from ReCaptcha V2, at NodeJS express API layer?
If yes, then is there any sample?
If not, then what is the standard way to verify it? ( other than calling google verify API endpoint, I know this, but here I need to send "secret key" as well, which I don't want to, hence the question )

**Comment by sagiavinash** [comment]
https://cloud.google.com/recaptcha-enterprise/docs/create-assessment#node.js

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this issue is persisting, please feel free to reopen there. Thank you!
