### ISSUE TITLE
Adding await in front of client.createAssessment() does not make it async because this method does not have .then()

### ISSUE THREAD

**Issue by 333one** [googleapis/nodejs-recaptcha-enterprise#259]
I believe the example under "Using the client library" may be wrong or incomplete.  

```
async function main(projectNumber) {
  ...
  await client.createAssessment(request);
}
```

The event loop goes right past await because client.createAssessment does not have a .then() method inside of it.  Await statements are ignored if they don't return a promise.

Maybe I'm using this wrong or missing something important but I think the example needs work.

**Comment by tmatsuo** [comment]
Hi @333one Thanks for the report. I took a quick look at the source:
https://github.com/googleapis/nodejs-recaptcha-enterprise/blob/0eb8b92cf7dcb1d0afa380f0c84a7bc0afc98453/protos/protos.d.ts#L61

The function signature indicates that it returns a promise.
What do you see if you change the code like:
```javascript
console.log(client.createAssessment(request));
```

It will show you the return type.

**Comment by 333one** [comment]
I just tested it with the _console.log_ and you are correct it comes back with [[PromiseStatus]] and [[PromiseValue]].

So in theory it should pause on the _await_ statement until the method returns but for some reason it goes past it every time.

`await client.createAssessment(request)`

I use it like below.  It hits the _await_, goes straight to the _return_ and later comes back and runs the method.

```
exports.recaptchaAssessment = function (token, actionToProtect) {

	const request = {
		// assemble request here.
	};

	let isTokenValid, isActionValid, didScorePass;
	isTokenValid = isActionValid = didScorePass = false;

	await client.createAssessment(request, function (err, response) {
		if (err) reject(err);

		if (response.tokenProperties.valid === true) isTokenValid = true;
		if (response.tokenProperties.action === actionToProtect) isActionValid = true;
		if (response.riskAnalysis.score >= captchaSafeScore) didScorePass = true;

		resolve({ isTokenValid, isActionValid, didScorePass });
	});

	return { isTokenValid, isActionValid, didScorePass };
```

I reworked it by wrapping it in a _Promise_ and it works as expected.

	```
return assessmentWrapper(request);

	function assessmentWrapper(request) {
		let isTokenValid, isActionValid, didScorePass;
		isTokenValid = isActionValid = didScorePass = false;

		return new Promise(function (resolve, reject) {
			client.createAssessment(request, function (err, response) {
				if (err) reject(err);

				if (response.tokenProperties.valid === true) isTokenValid = true;
				if (response.tokenProperties.action === actionToProtect) isActionValid = true;
				if (response.riskAnalysis.score >= captchaSafeScore) didScorePass = true;

				resolve({ isTokenValid, isActionValid, didScorePass });
			});
		});
	}****
```

You're right about the _Promise_ so maybe I'm doing something wrong but at least for me it blows past the _await_ every time.  However when I wrap it in a _Promise_ it works fine.

**Comment by tmatsuo** [comment]
There is an overloaded method:
https://github.com/googleapis/nodejs-recaptcha-enterprise/blob/0eb8b92cf7dcb1d0afa380f0c84a7bc0afc98453/protos/protos.d.ts#L54

This version returns void :)

**Comment by tmatsuo** [comment]
I think it's working as expected, closing. Feel free to re-open if you think differently :)
