### ISSUE TITLE
Score Based Recaptcha Enterprise always return 1.0 on Chrome Browser & 0.9 on IE, edge , Firefox & Safari Browser

### ISSUE THREAD

**Issue by parul7802** [googleapis/nodejs-recaptcha-enterprise#282]
Hey Team,

I have implemented Score Based reCaptcha on of my page . I'm using it in a way where after user enters the input on the form on a particular field & does tab-out , the Score Based reCaptcha will get executed .

I have observed a consistent behaviour where - I'm typing at any speed in Chrome - The score of the assessment is 1.0 
& for other browsers like  IE, edge , Firefox & Safari  - it is 0.9

The score is not at all changing & the behaviour is consistent . Anything on this ? 
FYI , I'm using AngularJS + nodeJS in my frontend

**Comment by sofisl** [comment]
Hi @parul7802,

Would you mind providing code/an environment to replicate this issue? Thanks.

**Comment by sofisl** [comment]
Closing this for now, feel free to open a new issue with more details!
