### ISSUE TITLE
Recaptcha enterprise is not identifying bot users.

### ISSUE THREAD

**Issue by Dinesh0098** [googleapis/nodejs-recaptcha-enterprise#308]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
- unsure where the issue exactly is.

2) Did someone already solve this?
- Nope, I haven't found the solution so far.

## Description
- Recaptcha should fail the action sign-in, sign-up If I am running this action with automation [ bot users].

#### Environment details

  - OS: windows 10
  - Node.js version: 14.17.5
  - npm version: 6.14.8
  - `@google-cloud/recaptcha-enterprise` version: 2.1.6

#### Steps to reproduce

  1. ? Run automation test for the simple sign-in form which has Recaptcha enterprise added in it.
  2. ? **And Recaptcha is verification passing the user, with token properties**
  
```
tokenProperties: {
      valid: true,
      invalidReason: 'INVALID_REASON_UNSPECIFIED',
      createTime: [Object],
      hostname: 'localhost',
      action: 'signIn'
    }
```

**Thanks!**

**Comment by bcoe** [comment]
@Dinesh0098 this is most likely an issue with the Recaptcha Enterprise product itself, not the client library.

You can open an issue with the product team [here](https://cloud.google.com/recaptcha-enterprise/docs/overview), by clicking "Send Feedback".

**Comment by Sita04** [comment]
@Dinesh0098 Could you provide more information on the type of recaptcha key you are using? Score or checkbox based?

Token validity is not correlated to the detection/ risk analysis. The validity of the token in the `Create Assessment` response only indicates that the reCAPTCHA server was able to successfully parse the request and create detection results. To read more about how to interpret the assessment, please refer to this [doc](https://cloud.google.com/recaptcha-enterprise/docs/interpret-assessment).

In case of a bot trying to login, the scores under [riskAnalysis](https://cloud.google.com/recaptcha-enterprise/docs/interpret-assessment#interpret_assessment) will be on the lower side of 0.0 to 1.0.

**Comment by Sita04** [comment]
Temporarily removing the assignment until we get more information.
@Dinesh0098 Feel free to assign me back.

**Comment by Sita04** [comment]
Hey, we couldn't reproduce and haven't heard back from you, so are going ahead and closing. If you continue to bump into issues, please let us know.
