### ISSUE TITLE
Puppeteer automation test always return score > 0.8

### ISSUE THREAD

**Issue by aplesss** [googleapis/nodejs-recaptcha-enterprise#407]
I using recaptcha enterprise client for node in NextJS server. 
**Environment details**
OS: MacOS 12.2.1 
Node.js version: 16.14.0
Next: 12.2.5
 Google-cloud/recaptcha-enterprise: 3.0.3
**Desciption**
Using pupperteer create automation test. But, the score always return > 0.8

**Comment by danielbankhead** [comment]
Hello! This issue tracker is designed for the library itself, but this sounds like an API-specific issue. Would you mind creating your issue here ([link](https://issuetracker.google.com/issues/new?component=840291)), and the product tea can take a look? Thank you!
